/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

/*
Model: https://www.cgtrader.com/3d-models/space/planet/planets-1
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
export default function AboutModel(props) {
  const aboutRef = useRef();

  const { nodes, materials } = useGLTF("models/about.glb");
  return (
    <group {...props} dispose={null} ref={aboutRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Planet_6.geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload("models/about.glb");
