/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from '@react-three/fiber';


export default function ContactModel(props) {
  const contactRef = useRef();

  useFrame(() => {
    contactRef.current.rotation.y -= 0.001;
  });
  const { nodes, materials } = useGLTF("models/contact.glb");
  return (
    <group {...props} dispose={null} ref={contactRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Planet_7.geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload("models/contact.glb");