/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from '@react-three/fiber';

export default function HomeModel(props) {
  const homeRef = useRef();

  useFrame(() => {
    homeRef.current.rotation.y -= 0.0001;
  });
  const { nodes, materials } = useGLTF("models/homePlanet.glb");
  return (
    <group {...props} dispose={null} ref={homeRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Planet_28.geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload("models/homePlanet.glb");