/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

/*
Model: https://www.cgtrader.com/3d-models/space/planet/planets-1
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function HomeModel(props) {
  const homeRef = useRef();
  const { nodes, materials } = useGLTF("models/homePlanet.glb");
  return (
    <group {...props} dispose={null} ref={homeRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Planet_28.geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload("models/homePlanet.glb");