/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useFrame } from '@react-three/fiber';
import { useGLTF } from "@react-three/drei";

export default function ResumeModel(props) {
  const { nodes, materials } = useGLTF("models/resume.glb");
  const resumeRef = useRef();

  useFrame(() => {
    resumeRef.current.rotation.y += 0.001;
  });

  return (
    <group {...props} dispose={null} ref={resumeRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Planet_40.geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload("models/resume.glb");