/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

/*
Model: https://www.cgtrader.com/3d-models/space/planet/planets-1
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function ResumeModel(props) {
  const { nodes, materials } = useGLTF("models/resume.glb");
  const resumeRef = useRef();


  return (
    <group {...props} dispose={null} ref={resumeRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Planet_40.geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload("models/resume.glb");