/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

/*
Model: https://www.cgtrader.com/3d-models/space/planet/planets-1
*/

import React, { useRef, useEffect, useState } from "react";
import * as THREE from 'three'
import { useGLTF, PerspectiveCamera } from "@react-three/drei";
import { useFrame } from '@react-three/fiber';
import { gsap } from "gsap";
import { MotionPathPlugin } from "gsap/MotionPathPlugin";
import { Timeline } from "gsap/gsap-core";

gsap.registerPlugin(MotionPathPlugin);


export default function Rocket(props) {
  const { nodes, materials } = useGLTF("models/rocket.glb");
  const [currentPlanet, setCurrentPlanet] = useState("home");
  const [destination, setDestination] = useState("home");
  const [targetCameraPosition, setTargetCameraPosition] = useState(new THREE.Vector3(40, 40, 40));
  const { home, about, contact, projects, resume } = props;
  const rocketPosition = new THREE.Vector3(0, 0, 0);
  const [isLanding, setIsLanding] = useState(false);
  const [midGlow, setMidGlow] = useState(false);
  const [turnOffGlow, setTurnOffGlow] = useState(false);
  const [landed, setLanded] = useState(true);
  const [glowIntensity, setGlowIntensity] = useState(15);

  const rocketRef = useRef();
  const camRef = useRef();
  const glowRef = useRef();

  const glowPositionOffset = new THREE.Vector3(0, -1, 0);
  const glowSize = { radius: 1, height: 2 };

  const planetPositions = {
    home: new THREE.Vector3(0, 0, 100),
    about: new THREE.Vector3(-175, 0, -100),
    contact: new THREE.Vector3(0, 0, -250),
    projects: new THREE.Vector3(325, 0, 0),
    resume: new THREE.Vector3(100, 0, 400)
  };

  const planetCameraPositions = {
    home: new THREE.Vector3(40, 40, 40),
    about: new THREE.Vector3(40, 40, 40),
    contact: new THREE.Vector3(40, 40, 40),
    projects: new THREE.Vector3(40, 40, 40),
    resume: new THREE.Vector3(30, 40, 40)
  };

  const navigateTo = (destination) => {
    const startPosition = planetPositions[currentPlanet];
    const endPosition = planetPositions[destination];
    const cameraEndPosition = planetCameraPositions[destination];

    setDestination(destination);
    animateRocketToPosition(startPosition, endPosition);
    setTargetCameraPosition(cameraEndPosition);
    setCurrentPlanet(destination);
  };

  function getDirectionToDestination(currentPosition, destinationPosition) {
    const direction = new THREE.Vector3().subVectors(destinationPosition, currentPosition);
    direction.normalize();
    return direction;
  }


  useEffect(() => {
    let newDestination = '';
    if (home) newDestination = 'home';
    else if (about) newDestination = 'about';
    else if (contact) newDestination = 'contact';
    else if (projects) newDestination = 'projects';
    else if (resume) newDestination = 'resume';

    if (newDestination && newDestination !== currentPlanet) {
      setDestination(newDestination);
      navigateTo(newDestination);
    }
  }, [home, about, contact, projects, resume]);

  const animateRocketToPosition = (startPosition, endPosition) => {
    if (!rocketRef.current) return;
    const landingPhase = 0.20;
    const glowPhase = 0.95;
    const midGlow = 0.5;
    const landed = 1;
    setLanded(false);

    const midPosition = new THREE.Vector3().addVectors(startPosition, endPosition).multiplyScalar(0.5).add(new THREE.Vector3(0, 100, 0));
    const hCMid = new THREE.Vector3().addVectors(startPosition, endPosition).multiplyScalar(0.5).add(new THREE.Vector3(0, 200, 0));

    var curve = new THREE.CatmullRomCurve3([startPosition, midPosition, endPosition], false, 'centripetal', 0.5);

    if (startPosition === planetPositions.home && endPosition === planetPositions.contact || startPosition === planetPositions.contact && endPosition === planetPositions.home) {
      curve = new THREE.CatmullRomCurve3([startPosition, hCMid, endPosition], false, 'centripetal', 0.5);
    }

    gsap.to({ t: 0 }, {
      t: 1,
      duration: 6,
      onUpdate: function () {
        const position = curve.getPointAt(this.targets()[0].t);
        rocketRef.current.position.copy(position);
        setIsLanding(this.targets()[0].t > landingPhase);
        setMidGlow(this.targets()[0].t > midGlow);
        setTurnOffGlow(this.targets()[0].t > glowPhase);

      },
      onComplete: function () {
        setLanded(true);
      },
      ease: "expo.inOut"
    });
  };


  useFrame((state, delta) => {
    if (!rocketRef.current) return;
    const time = state.clock.getElapsedTime();

    const rocketPosition = new THREE.Vector3().setFromMatrixPosition(rocketRef.current.matrixWorld);
    const destinationPosition = planetPositions[destination];

    if (midGlow) {
      const midOpacity = 0;
      glowRef.current.material.opacity = midOpacity;
    }

    if (midGlow && turnOffGlow) {
      const offOpacity = 0.5;
      glowRef.current.material.opacity = offOpacity;
    }

    if (landed) {
      const landedOpacity = 0;
      glowRef.current.material.opacity = landedOpacity;
      setGlowIntensity(0);
    }

    const radius = 40;
    const cameraX = rocketPosition.x + radius;
    const cameraZ = rocketPosition.z + radius;
    const x = cameraX * Math.cos(time * 0.02);
    const z = cameraZ * Math.sin(time * 0.02);
    state.camera.position.set(x, 10, z);
    state.camera.lookAt(rocketPosition);





    if (isLanding) {
      const uprightQuaternion = new THREE.Quaternion();
      rocketRef.current.quaternion.slerp(uprightQuaternion, 0.75 * delta);
    } else {
      const directionToDestination = getDirectionToDestination(rocketPosition, destinationPosition);
      const rocketQuaternion = new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0, 1, 0), directionToDestination);
      rocketRef.current.quaternion.slerp(rocketQuaternion, 0.5 * delta);
    }
  });

  return (
    <group {...props} dispose={null} ref={rocketRef}>
      <group>
        <group
          position={[0, 1.673, 0.663]}
          rotation={[1.394, 0, 0]}
          scale={0.431}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_1.geometry}
            material={materials.purple2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_2.geometry}
            material={materials.bLUE}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCircle.geometry}
          material={materials.purple2}
          position={[-0.274, -0.239, 0.158]}
          rotation={[1.346, -0.368, -0.566]}
          scale={0.852}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCircle001.geometry}
          material={materials.purple2}
          position={[0, -0.239, -0.316]}
          rotation={[1.999, 0, 1.57]}
          scale={0.852}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCircle002.geometry}
          material={materials.purple2}
          position={[0.274, -0.239, 0.158]}
          rotation={[1.346, 0.368, -2.577]}
          scale={0.852}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials.Red}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials.White}
        />
      </group>
      <group>
        <mesh
          ref={glowRef}
          position={[glowPositionOffset.x, glowPositionOffset.y, glowPositionOffset.z]}
        >
          <coneGeometry attach="geometry" args={[glowSize.radius, glowSize.height, 8, 4, true]} />
          <meshBasicMaterial attach="material" color="orange" transparent={true} opacity={0.5} side={THREE.DoubleSide} />
        </mesh>
        <pointLight
          intensity={glowIntensity}
          distance={15}
          decay={1}
          color={"orange"}
          position={[glowPositionOffset.x, glowPositionOffset.y, glowPositionOffset.z]}
        />
        <PerspectiveCamera
          makeDefault
          fov={75}
          position={planetCameraPositions[currentPlanet]}
          useRef={camRef}
        >
        </PerspectiveCamera>
      </group>
    </group>
  );
}

useGLTF.preload("models/rocket.glb");
