/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, memo } from "react";
import { useGLTF } from "@react-three/drei";
import { Bloom, EffectComposer } from "@react-three/postprocessing";

const SunModel = memo(function SunModel(props) {
    const { nodes, materials } = useGLTF("/sun.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Planet_27.geometry}
                material={materials.Material}
            />
            <EffectComposer>
                <Bloom
                    intensity={0.5}
                    luminanceThreshold={0.15}
                    luminanceSmoothing={0.3}
                />
            </EffectComposer>
        </group>
    );
});

useGLTF.preload("/sunModel.glb");
export default SunModel;