/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

/*
Model: https://www.cgtrader.com/3d-models/space/planet/planets-1
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, extend } from '@react-three/fiber';
import { MeshStandardMaterial } from 'three';
import { EffectComposer, Bloom } from '@react-three/postprocessing';

extend({ MeshStandardMaterial });


export default function SunModel(props) {
  const aboutRef = useRef();

  useFrame(() => {
    aboutRef.current.rotation.y += 0.001;
    aboutRef.current.rotation.x += 0.001;
  });

  const { nodes, materials } = useGLTF("models/about.glb");

  return (
    <group {...props} dispose={null} ref={aboutRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Planet_6.geometry}
      >
        <meshStandardMaterial
          emissive={'#ffff00'} // Adjust the color to your liking
          emissiveIntensity={0.80} // Adjust the intensity as needed
          // You can also spread the original material properties if needed:
          material={materials.Material}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("models/about.glb");

